[package]
name = "mdedit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20"
log = "0.4"
simple-logging = "2.0.2"
unicode-width = "0.1.5"
queues = "1.0.2"
